---
title: "Exams"
author: "Aaron Vick"
date: "2022-11-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rpart)
library(caret)
library(tidyverse)
library(rpart.plot)
```

```{r data gathering}

set.seed(542)

DATA <- read.csv("Exams.csv")

DATA$Final_Grade <- (DATA$math.score + DATA$reading.score + DATA$writing.score) / 3
DATA$Passing <- ifelse(DATA$Final_Grade >= 70, 1, 0)
DATA$Passing.fac <- as.factor(ifelse(DATA$Passing == 1, "yes", "no"))

DATA <- DATA %>% select(1:5, 11)

train_rows <- sample(1:nrow(DATA), size = nrow(DATA) / 2
                     , replace = F)

train_set <- DATA[train_rows,]
test_set <- DATA[-train_rows,]

```

```{r decision tree}

set.seed(542)

ExamTree <- rpart(Passing.fac ~ ., data = train_set)
ExamTree
prp(ExamTree, box.palette = "Reds", tweak = 1.2)

results <- predict(ExamTree, test_set, type="class")
confusionMatrix(test_set$Passing.fac, results)

```

```{r decision tree with cross validation}

set.seed(542)

tC <- trainControl(method = "cv", 
             number = 10, 
             savePredictions = TRUE, 
             classProbs = TRUE, 
             verboseIter = TRUE)

dccv <- train(Passing.fac ~ ., 
            method = "rpart", 
            trControl = tC, 
            preProcess = c("center","scale"), 
            data = train_set)

prp(dccv$finalModel, box.palette = "Reds", tweak = 1.2)

dccv$results[1, 2]

dccv$results[1, 2] + c(-2, 2) * dccv$results[1, 4]

```


```{r random forest}

set.seed(542)

tC <- trainControl(method = "cv", 
             number = 10, 
             savePredictions = TRUE, 
             classProbs = TRUE, 
             verboseIter = TRUE)

rf <- train(Passing.fac ~ ., 
            method = "rf", 
            trControl = tC, 
            preProcess = c("center","scale"), 
            ntree = 50,
            data = train_set)

rf$results[2, 2]

rf$results[2, 2] + c(-2, 2) * dccv$results[2, 4]

```

